[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -m src.app.main"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
healthcheckPath = ""
healthcheckTimeout = 120
